# Generated by Django 5.2.8 on 2025-11-20 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('launch_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpaceAgency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('founded', models.IntegerField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Satellite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('orbit_type', models.CharField(max_length=50)),
                ('purpose', models.CharField(max_length=200)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='starlinker.mission')),
            ],
        ),
        migrations.AddField(
            model_name='mission',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='starlinker.spaceagency'),
        ),
    ]
