# Generated by Django 5.2.8 on 2025-11-21 04:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starlinker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='mission_images/'),
        ),
        migrations.AddField(
            model_name='spaceagency',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='agency_logos/'),
        ),
        migrations.CreateModel(
            name='FavoriteMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='starlinker.mission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'mission')},
            },
        ),
    ]
