# Generated by Django 5.2.8 on 2025-11-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starlinker', '0002_mission_image_spaceagency_logo_favoritemission'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='orbit_type',
            field=models.CharField(choices=[('LEO', 'Low Earth Orbit'), ('MEO', 'Medium Earth Orbit'), ('GEO', 'Geostationary Orbit'), ('HEO', 'High Earth Orbit'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AlterField(
            model_name='satellite',
            name='orbit_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
